#ifndef LOGICGATESYMBOLS_GLOBAL_H
#define LOGICGATESYMBOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGICGATESYMBOLS_LIBRARY)
#define LOGICGATESYMBOLS_EXPORT Q_DECL_EXPORT
#else
#define LOGICGATESYMBOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGICGATESYMBOLS_GLOBAL_H
